<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Azure File Share Storage provider for Centeva.ObjectStorage</Description>
    <PackageIconUrl>icon.png</PackageIconUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" />
    <PackageReference Include="Azure.Storage.Files.Shares" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Centeva.ObjectStorage\Centeva.ObjectStorage.csproj" />
  </ItemGroup>

  <ItemGroup>
    <!-- Needed for nuget package -->
    <None Include="..\..\README.md" Pack="true" PackagePath="" />
    <None Include="..\..\icon.png" Pack="true" PackagePath="" />
  </ItemGroup>

</Project>
