name: Build and Test

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request_target: # Needed to access secrets
    branches: [main]
jobs:
  build:
    runs-on: [self-hosted, linux]

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        env:
          AwsTestBucketName: ${{ vars.AWS_TEST_BUCKET_NAME }}
          AwsTestBucketRegion: ${{ vars.AWS_TEST_BUCKET_REGION }}
          AwsAccessKey: ${{ secrets.AWS_ACCESS_KEY }}
          AwsSecretKey: ${{ secrets.AWS_SECRET_KEY }}
          AzureBlobStorageTestContainerName: ${{ vars.AZURE_BLOB_STORAGE_TEST_CONTAINER_NAME }}
          AzureAccountName: ${{ secrets.AZURE_ACCOUNT_NAME }}
          AzureAccountKey: ${{ secrets.AZURE_ACCOUNT_KEY }}
          GoogleStorageTestBucketName: ${{ vars.GOOGLE_STORAGE_TEST_BUCKET_NAME }}
          GoogleStorageCredentialsJson: ${{ secrets.GOOGLE_STORAGE_CREDENTIALS_JSON }}
        run: dotnet test --no-build --configuration Release
