name: Release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-pre.[0-9]+"
jobs:
  package:
    name: Publish Package

    runs-on: [self-hosted, linux]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # - name: Verify commit is on main for safety
      #   run: git branch --remote --contains | grep origin/main

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v2
        with:
          versionSpec: "5.x"

      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v2
        id: gitversion
        with:
          useConfigFile: true

      # - name: Extract release notes
      #   run: |
      #     git log --pretty=format:'%d %s' ${GITHUB_REF} | perl -pe 's| \(.*tag: v(\d+.\d+.\d+(-preview\d{3})?)(, .*?)*\)|\n## \1\n|g' > RELEASE-NOTES

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          source-url: https://nuget.pkg.github.com/centeva/index.json
          dotnet-version: |
            8.x
            9.x
        env:
          DOTNET_INSTALL_DIR: '~/dotnet'
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Build
        run: dotnet build --configuration Release /p:Version=${{ steps.gitversion.outputs.semVer }}

      - name: Test
        env:
          AwsTestBucketName: ${{ vars.AWS_TEST_BUCKET_NAME }}
          AwsTestBucketRegion: ${{ vars.AWS_TEST_BUCKET_REGION }}
          AwsAccessKey: ${{ secrets.AWS_ACCESS_KEY }}
          AwsSecretKey: ${{ secrets.AWS_SECRET_KEY }}
          AzureBlobStorageTestContainerName: ${{ vars.AZURE_BLOB_STORAGE_TEST_CONTAINER_NAME }}
          AzureAccountName: ${{ secrets.AZURE_ACCOUNT_NAME }}
          AzureAccountKey: ${{ secrets.AZURE_ACCOUNT_KEY }}
          GoogleStorageTestBucketName: ${{ vars.GOOGLE_STORAGE_TEST_BUCKET_NAME }}
          GoogleStorageCredentialsJson: ${{ secrets.GOOGLE_STORAGE_CREDENTIALS_JSON }}
        run: dotnet test --configuration Release /p:Version=${{ steps.gitversion.outputs.semVer }} --no-build

      - name: Package
        run: dotnet pack --configuration Release /p:Version=${{ steps.gitversion.outputs.semVer }} --no-build --output packages

      - name: Push to Github Packages
        run: dotnet nuget push packages/*.nupkg --api-key ${{secrets.GITHUB_TOKEN}}

      - name: Push to nuget.org
        run: dotnet nuget push packages/*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
